In [2]:
from numpy import array

i_hat1 = array([0,1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

print(i_hat1)
print(j_hat1)
print(transform1)


[0 1]
[-1  0]
[[ 0 -1]
 [ 1  0]]


In [6]:
i_hat2 = array([1,0])
j_hat2 = array([1,1])
transform2 = array([i_hat2, j_hat2]).transpose()

print(transform2)

[[1 1]
 [0 1]]


In [8]:
combined = transform1 @ transform2

print(combined)

[[ 0 -1]
 [ 1  1]]


### ex.4-13

In [9]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


In [10]:
from sympy import *

A = Matrix([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])

inverse = A.inv()
identity = inverse*A

print(inverse)
print(identity)

ModuleNotFoundError: No module named 'sympy'

In [12]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecss = eig(A)
print(eigenvals)
print(eigenvecss)

[-0.46410162  6.46410162]
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
