In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [9]:
all_data = pd.read_csv("simple2.csv")

In [28]:
all_data.iloc[:,0:3].max()

RED      255
GREEN    255
BLUE     255
dtype: int64

In [15]:
all_inputs = (all_data.iloc[:, 0:3].values / 255.0)
all_outputs = all_data.iloc[:, -1].values

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(all_inputs, all_outputs, test_size = 1/3)
n = X_train.shape[0]

In [32]:
X_train

array([[0.93333333, 0.8627451 , 0.50980392],
       [1.        , 0.07843137, 0.57647059],
       [0.        , 0.54509804, 0.27058824],
       ...,
       [0.        , 0.60392157, 0.80392157],
       [0.5372549 , 0.40784314, 0.80392157],
       [0.63529412, 0.70980392, 0.80392157]], shape=(896, 3))

In [30]:
w_hidden = np.random.rand(3,3)
w_output = np.random.rand(1,3)

In [33]:
w_hidden

array([[0.66352906, 0.49217965, 0.3839572 ],
       [0.71124687, 0.93604737, 0.32660059],
       [0.70857551, 0.51698131, 0.73680849]])

In [34]:
w_output

array([[0.97318763, 0.17427556, 0.50159111]])

In [35]:
b_hidden = np.random.rand(3,1)
b_output = np.random.rand(1,1)

In [44]:
relu = lambda x: np.maximum(x, 0)
logistic = lambda x: 1 / (1 + np.exp(-x))

In [45]:
def forward_prop(X):
    Z1 = w_hidden @ X + b_hidden
    A1 = relu(Z1)
    Z2 = w_output @ A1 + b_output
    A2 = logistic(Z2)
    return Z1, A1, Z2, A2

In [49]:
train_predictions = forward_prop(X_train.transpose())[3]

In [50]:
train_comparisons = np.equal((train_predictions >= 0.5).flatten().astype(int), Y_train)

In [51]:
accuracy = sum(train_comparisons.astype(int) / X_train.shape[0])
print("정확도: ", accuracy)

정확도:  0.6294642857142867
